version: "3.8"

services:
  # Laravel + Apache
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sven-backend
    ports: ["8000:80"]
    depends_on: [mysql]
    volumes:
      - ./backend/laravel:/var/www/html/laravel
    working_dir: /var/www/html/laravel
    command: bash -c "chmod +x ./setup.sh && dos2unix ./setup.sh && ./setup.sh"

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplay
      MYSQL_PASSWORD: root
    ports: 
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "30050:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"

volumes:
  mysql_data:
